#!/bin/bash

#Include utils script
source "$(dirname $(readlink -f $0))/utils.sh"

if ! $CONF_commit_msg_active ; then
    #The hook is not active
    exit 0
fi

#First parameter passed to script contains the file 
#where the commit message is stored
commitMessage=$(<"$1")
if [[ ! $commitMessage =~ $CONF_commit_msg_regex ]]; then
    printf "Commit message should be in the format $CONF_commit_msg_regex\n"
    exit 1
fi
exit 0
